### ISSUE TITLE
example of use

### ISSUE THREAD

**Issue by Yardie-** [jkent/esp32-sqlite3#1]
Hi I am not sure if you are still interested in this however. I was wondering if you have a simple example of how you used this library.
Thanks.
:) Greg

**Comment by jkent** [comment]
Nope sorry, I never used it in production.  The project it was intended for was canceled.  Sorry!

**Comment by Yardie-** [comment]
Ok that's fine. I'm getting core dumps on sqlite3_exec on an external flash with a fat filesystem.

But your code does compile on esp-idf v4 and it does create the database so it's a good place to start thanks.
